name: dandn_admin_simple
description: "نظام دندن الإداري المبسط - لوحة تحكم Flutter Web"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Supabase
  supabase_flutter: ^2.8.0
  
  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  
  # Routing
  go_router: ^14.2.7
  
  # UI Components
  google_fonts: ^6.2.1
  
  # Charts
  fl_chart: ^0.69.0
  
  # Utilities
  intl: ^0.20.2
  
  # HTTP
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

